BEGIN;

-- ============================================================
-- PHASE 027D-4
-- Automatic 5 -> 20 Promotion Watcher
--
-- PURPOSE
--   Automatically promote SlateLane from protected 5-carrier
--   capacity to protected 20-carrier capacity ONLY when the
--   existing activation gate becomes READY.
--
-- SAFETY
--   * Does NOT send email.
--   * Does NOT create leads.
--   * Does NOT create enrollments.
--   * Does NOT arm the prepared batch.
--   * Does NOT enable master sending.
--   * Does NOT interfere with the currently running pilot.
-- ============================================================


-- ============================================================
-- 1. PROMOTION AUDIT TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS public.email_ramp_20_promotion_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    prepared_batch_id uuid,

    gate_status text,
    gate_reason text,

    previous_pilot_limit integer,
    new_pilot_limit integer,

    previous_daily_send_cap integer,
    new_daily_send_cap integer,

    previous_max_batch_size integer,
    new_max_batch_size integer,

    sending_enabled_before boolean,
    sending_enabled_after boolean,

    pilot_mode_before boolean,
    pilot_mode_after boolean,

    promoted_at timestamptz NOT NULL DEFAULT now(),

    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);


CREATE INDEX IF NOT EXISTS
    email_ramp_20_promotion_audit_promoted_at_idx
ON public.email_ramp_20_promotion_audit (
    promoted_at DESC
);


-- ============================================================
-- 2. GUARDED AUTOMATIC PROMOTION FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION
public.promote_email_ramp_20_capacity_if_ready()
RETURNS jsonb

LANGUAGE plpgsql
SECURITY DEFINER

SET search_path = public, pg_temp

AS $$

DECLARE

    v_settings_id integer;

    v_sending_enabled boolean;
    v_daily_send_cap integer;
    v_max_batch_size integer;
    v_pilot_mode boolean;
    v_pilot_limit integer;

    v_gate_status text;
    v_ready_for_activation boolean;
    v_gate_reason text;

    v_prepared_batch_id uuid;
    v_prepared_count integer;

BEGIN

    -- ========================================================
    -- LOAD + LOCK CURRENT LAUNCH SETTINGS
    -- ========================================================

    SELECT
        id,
        sending_enabled,
        daily_send_cap,
        max_batch_size,
        pilot_mode,
        pilot_limit

    INTO
        v_settings_id,
        v_sending_enabled,
        v_daily_send_cap,
        v_max_batch_size,
        v_pilot_mode,
        v_pilot_limit

    FROM public.email_launch_settings

    ORDER BY id

    LIMIT 1

    FOR UPDATE;


    IF v_settings_id IS NULL THEN

        RETURN jsonb_build_object(

            'phase',
            '027D4-automatic-5-to-20-promotion-watcher',

            'success',
            false,

            'promoted',
            false,

            'reason',
            'email_launch_settings_missing',

            'message',
            'Promotion refused because email launch settings do not exist.'

        );

    END IF;


    -- ========================================================
    -- ABSOLUTE MASTER-SENDING SAFETY
    --
    -- Automatic capacity promotion is only allowed while
    -- sending is disabled.
    -- ========================================================

    IF COALESCE(
        v_sending_enabled,
        false
    ) = true THEN

        RETURN jsonb_build_object(

            'phase',
            '027D4-automatic-5-to-20-promotion-watcher',

            'success',
            false,

            'promoted',
            false,

            'reason',
            'master_sending_already_enabled',

            'message',
            'Promotion refused because master sending is already enabled.',

            'current_state',
            jsonb_build_object(

                'pilot_limit',
                v_pilot_limit,

                'daily_send_cap',
                v_daily_send_cap,

                'max_batch_size',
                v_max_batch_size,

                'pilot_mode',
                v_pilot_mode,

                'sending_enabled',
                v_sending_enabled

            )

        );

    END IF;


    -- ========================================================
    -- READ EXISTING PHASE 027D3 ACTIVATION GATE
    -- ========================================================

    SELECT

        gate_status,
        ready_for_activation,
        reason,
        prepared_batch_id,
        prepared_count

    INTO

        v_gate_status,
        v_ready_for_activation,
        v_gate_reason,
        v_prepared_batch_id,
        v_prepared_count

    FROM public.email_ramp_20_activation_status

    LIMIT 1;


    IF NOT FOUND THEN

        RETURN jsonb_build_object(

            'phase',
            '027D4-automatic-5-to-20-promotion-watcher',

            'success',
            false,

            'promoted',
            false,

            'reason',
            'activation_status_missing',

            'message',
            'Promotion refused because the Phase 027D3 activation status is unavailable.'

        );

    END IF;


    -- ========================================================
    -- IDEMPOTENCY
    --
    -- If already promoted, do nothing.
    -- ========================================================

    IF

        COALESCE(
            v_pilot_limit,
            0
        ) >= 20

        AND

        COALESCE(
            v_daily_send_cap,
            0
        ) >= 20

    THEN

        RETURN jsonb_build_object(

            'phase',
            '027D4-automatic-5-to-20-promotion-watcher',

            'success',
            true,

            'promoted',
            false,

            'already_promoted',
            true,

            'reason',
            'capacity_already_20',

            'message',
            'Protected 20-carrier capacity is already configured.',

            'state',
            jsonb_build_object(

                'pilot_limit',
                v_pilot_limit,

                'daily_send_cap',
                v_daily_send_cap,

                'max_batch_size',
                v_max_batch_size,

                'pilot_mode',
                v_pilot_mode,

                'master_sending',
                v_sending_enabled

            )

        );

    END IF;


    -- ========================================================
    -- THE CRITICAL GATE
    --
    -- While the current 5-carrier pilot is active,
    -- this block returns safely WITHOUT MUTATION.
    -- ========================================================

    IF

        COALESCE(
            v_ready_for_activation,
            false
        ) = false

        OR

        COALESCE(
            v_gate_status,
            ''
        ) <> 'READY'

    THEN

        RETURN jsonb_build_object(

            'phase',
            '027D4-automatic-5-to-20-promotion-watcher',

            'success',
            true,

            'promoted',
            false,

            'gate_status',
            v_gate_status,

            'reason',
            COALESCE(
                v_gate_reason,
                'promotion_gate_locked'
            ),

            'message',
            'No promotion performed. The protected 5-to-20 transition gate is still locked.',

            'prepared_batch',
            jsonb_build_object(

                'batch_id',
                v_prepared_batch_id,

                'prepared_count',
                v_prepared_count

            ),

            'current_capacity',
            jsonb_build_object(

                'pilot_limit',
                v_pilot_limit,

                'daily_send_cap',
                v_daily_send_cap,

                'max_batch_size',
                v_max_batch_size

            ),

            'protection',
            jsonb_build_object(

                'sends_email',
                false,

                'creates_leads',
                false,

                'creates_enrollments',
                false,

                'arms_prepared_batch',
                false,

                'enables_master_sending',
                false

            )

        );

    END IF;


    -- ========================================================
    -- PREPARED BATCH MUST ACTUALLY CONTAIN 20
    -- ========================================================

    IF COALESCE(
        v_prepared_count,
        0
    ) < 20 THEN

        RETURN jsonb_build_object(

            'phase',
            '027D4-automatic-5-to-20-promotion-watcher',

            'success',
            false,

            'promoted',
            false,

            'gate_status',
            v_gate_status,

            'reason',
            'prepared_batch_incomplete',

            'message',
            'Promotion refused because the protected batch contains fewer than 20 carriers.',

            'prepared_count',
            COALESCE(
                v_prepared_count,
                0
            )

        );

    END IF;


    -- ========================================================
    -- PROTECTED CAPACITY PROMOTION
    --
    -- IMPORTANT:
    -- sending_enabled remains FALSE.
    --
    -- Nothing gets transmitted here.
    -- ========================================================

    UPDATE public.email_launch_settings

    SET

        pilot_limit = 20,

        daily_send_cap = 20,

        max_batch_size = 5,

        pilot_mode = true,

        sending_enabled = false

    WHERE id = v_settings_id;


    -- ========================================================
    -- IMMUTABLE AUDIT EVENT
    -- ========================================================

    INSERT INTO public.email_ramp_20_promotion_audit (

        prepared_batch_id,

        gate_status,
        gate_reason,

        previous_pilot_limit,
        new_pilot_limit,

        previous_daily_send_cap,
        new_daily_send_cap,

        previous_max_batch_size,
        new_max_batch_size,

        sending_enabled_before,
        sending_enabled_after,

        pilot_mode_before,
        pilot_mode_after,

        metadata

    )

    VALUES (

        v_prepared_batch_id,

        v_gate_status,
        v_gate_reason,

        v_pilot_limit,
        20,

        v_daily_send_cap,
        20,

        v_max_batch_size,
        5,

        v_sending_enabled,
        false,

        v_pilot_mode,
        true,

        jsonb_build_object(

            'phase',
            '027D4',

            'transition',
            '5_to_20',

            'prepared_count',
            v_prepared_count,

            'automatic',
            true,

            'email_sent',
            false,

            'batch_armed',
            false,

            'enrollments_created',
            false

        )

    );


    -- ========================================================
    -- SUCCESS RESPONSE
    -- ========================================================

    RETURN jsonb_build_object(

        'phase',
        '027D4-automatic-5-to-20-promotion-watcher',

        'success',
        true,

        'promoted',
        true,

        'gate_status',
        v_gate_status,

        'message',
        'Protected capacity automatically promoted from 5 to 20. Master sending remains OFF.',

        'prepared_batch',
        jsonb_build_object(

            'batch_id',
            v_prepared_batch_id,

            'prepared_count',
            v_prepared_count

        ),

        'previous_capacity',
        jsonb_build_object(

            'pilot_limit',
            v_pilot_limit,

            'daily_send_cap',
            v_daily_send_cap,

            'max_batch_size',
            v_max_batch_size

        ),

        'new_capacity',
        jsonb_build_object(

            'pilot_limit',
            20,

            'daily_send_cap',
            20,

            'max_batch_size',
            5,

            'pilot_mode',
            true,

            'master_sending',
            false

        ),

        'protection',
        jsonb_build_object(

            'email_sent',
            false,

            'leads_created',
            false,

            'enrollments_created',
            false,

            'prepared_batch_armed',
            false,

            'master_sending_enabled',
            false

        )

    );

END;

$$;


-- ============================================================
-- 3. PROTECT THE EXECUTOR
-- ============================================================

REVOKE ALL

ON FUNCTION
public.promote_email_ramp_20_capacity_if_ready()

FROM PUBLIC;


GRANT EXECUTE

ON FUNCTION
public.promote_email_ramp_20_capacity_if_ready()

TO service_role;


-- ============================================================
-- 4. AUTOMATIC PROMOTION WATCHER
--
-- Runs every 5 minutes.
--
-- While current pilot is running:
--      no mutation
--
-- Once Phase 027D3 gate becomes READY:
--      capacity changes 5 -> 20
--
-- Master sending stays OFF.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pg_cron;


DO $$

DECLARE
    v_job_id bigint;

BEGIN

    SELECT jobid

    INTO v_job_id

    FROM cron.job

    WHERE jobname =
        'slatelane-ramp-20-promotion-watcher'

    LIMIT 1;


    IF v_job_id IS NOT NULL THEN

        PERFORM cron.unschedule(
            v_job_id
        );

    END IF;

END

$$;


SELECT cron.schedule(

    'slatelane-ramp-20-promotion-watcher',

    '*/5 * * * *',

    $cron$

        SELECT
            public.promote_email_ramp_20_capacity_if_ready();

    $cron$

);


COMMIT;